# Generated by Django 3.2.23 on 2024-02-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='location_detail',
            field=models.TextField(blank=True),
        ),
    ]
